# Generated by Django 3.1.7 on 2021-03-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210308_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
