# Generated by Django 3.1.7 on 2021-03-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_issue_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='description',
            new_name='description_md',
        ),
    ]
