# Generated by Django 3.1.7 on 2021-03-10 18:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import projects.utils


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_issue_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('INPROG', 'In progress'), ('REVIEW', 'Review'), ('DONE', 'Done')], default='TODO', max_length=8),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projects.utils.issue_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('txt', 'pdf', 'xml', 'doc', 'jpg', 'png'))])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.issue')),
            ],
        ),
    ]
