# Generated by Django 3.1.7 on 2021-03-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210311_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description_md',
            field=models.TextField(blank=True, default=''),
        ),
    ]
